# Generated by Django 4.1 on 2022-08-19 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_author_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
