# Generated by Django 4.1 on 2022-08-23 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_book_authors_delete_author_delete_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='last_bid',
            field=models.FloatField(blank=True, max_length=20, null=True),
        ),
    ]
