# Generated by Django 4.1 on 2022-08-25 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_auctionlisting_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='last_bid',
        ),
        migrations.RemoveField(
            model_name='bidprice',
            name='last_price',
        ),
        migrations.AddField(
            model_name='bidprice',
            name='last_bid',
            field=models.FloatField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bidprice',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bidprice',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.auctionlisting'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.auctionlisting'),
        ),
    ]
