# Generated by Django 4.1 on 2022-08-25 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_auctionlisting_last_bid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidprice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
